# 配置日志
logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs/${COMPOSE_PROJECT_NAME}
  level:
    org:
      springframework:
        security: debug
        modulith: debug
        web.reactive: debug
      babyfish.jimmer: debug
      flywaydb: debug

server:
  port: ${WEB_EXPOSE_PORT}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: ${COMPOSE_PROJECT_NAME}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST_PORT}/${DATABASE_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: ${DATABASE_DEFAULT_SCHEMA}
  webflux:
    problemdetails:
      enabled: true


jwt:
  secret: ${JWT_SECRET:secret}
  expiration-min: ${JWT_EXPIRATION_MIN:1440}
  expiration-max: ${JWT_EXPIRATION_MIN:10080}

jimmer:
  language: kotlin
  show-sql: true
  pretty-sql: true
  inline-sql-variables: true
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
