CREATE SCHEMA IF NOT EXISTS llmhub;

CREATE TABLE llmhub."user"
(
    "id"          BIGINT    NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "username"    VARCHAR   NOT NULL UNIQUE,
    "create_time" TIMESTAMP NOT NULL DEFAULT now(),
    "password"    VARCHAR   NOT NULL,
    "enable"      BOOLEAN   NOT NULL DEFAULT true,
    PRIMARY KEY ("id")
);

CREATE TABLE llmhub."permission"
(
    "id"   BIGINT  NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "code" VARCHAR NOT NULL,
    "name" VARCHAR NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE llmhub."role"
(
    "id"   BIGINT  NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "code" VARCHAR NOT NULL,
    "name" VARCHAR NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE llmhub."role_permission_map"
(
    "role_id"       BIGINT NOT NULL,
    "permission_id" BIGINT NOT NULL,
    PRIMARY KEY ("role_id","permission_id")
);

CREATE TABLE llmhub."user_role_map"
(
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    PRIMARY KEY ("user_id","role_id")
);


ALTER TABLE "llmhub"."role_permission_map" ADD FOREIGN KEY ("role_id") REFERENCES "llmhub"."role"("id") ON DELETE CASCADE;
ALTER TABLE "llmhub"."role_permission_map" ADD FOREIGN KEY ("permission_id") REFERENCES "llmhub"."permission"("id") ON DELETE CASCADE;
ALTER TABLE "llmhub"."user_role_map" ADD FOREIGN KEY ("role_id") REFERENCES "llmhub"."role"("id") ON DELETE CASCADE;
ALTER TABLE "llmhub"."user_role_map" ADD FOREIGN KEY ("user_id") REFERENCES "llmhub"."user"("id") ON DELETE CASCADE;
